name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro Max']

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
      xcodebuild clean test -project HerHack.xcodeproj -scheme HerHack -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGN
    - name: Run tests
      run: swift test -v
